name = "daily-stoic"
compatibility_date = "2025-05-05"
pages_build_output_dir = "dist" 

compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SESSION", id = "a31a1dfd8e6442f6a7441ccf03e59669" }
]